#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path './lib'

require 'simple_commander/import'
require './helpers/http_helper'

program :name, 'ember-c'
program :version, '0.0.1'
program :description, 'implementing ember with modified commander'
helpers 'IO', 'HTTP'

command :new do
	syntax = 'ember-c new <name>'
	summary = 'create a new ember project'
	description = 'Create a new ember project'
	action do |args, options|
		run_cmd(File.expand_path './') do
			say `ls`
		end
		http_get
	end
end

# new spec
#command :deploy do
#	helpers :io, :http
#
#	command :heroku do
#		actions_ext './deploy/heroku'
#	end
#
#	command :s3 do
#		actions_ext './deploy/s3'
#	end
#end
