#!/usr/bin/env ruby

require 'rubygems'
require 'commander'

class MyApplication
  include Commander::Methods
  # include whatever modules you need

  def run
    program :name, 'todo'
    program :version, '0.0.1'
    program :description, 'todo'

    command :add do |c|
			c.action do |args, options|
				case args[0]	
				when "something"
					puts "something"
				when "another"
					puts "another"
				end
			end
    end

    run!
  end
end

MyApplication.new.run if $0 == __FILE__
